arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n/generated
preferred-supported-locales: [en, zh_TW, zh_CN, ja]
nullable-getter: false
synthetic-package: false
