// AUTO-GENERATED by scripts/generate-gemini-defaults.mjs — do not edit.
// Regenerate: node scripts/generate-gemini-defaults.mjs
// CI: GitHub Variables → same env names, then npm run build.

export const geminiGeneratedDefaults = {
  defaultVisionModel: "gemini-2.5-flash",
  defaultEmbeddingModel: "gemini-embedding-exp-03-07",
  deprecatedVisionModelIds: ["gemini-1.5-flash","gemini-1.5-flash-8b","gemini-1.5-pro","gemini-2.0-flash"],
  deprecatedEmbeddingModelIds: ["text-embedding-001","embedding-001","text-embedding-004"],
  visionFallbackChain: ["gemini-2.5-flash","gemini-2.0-flash"],
  embeddingFallbackChain: ["gemini-embedding-exp-03-07"],
} as const;
